### ISSUE TITLE
References missing in PDF on GitHub

### ISSUE THREAD

**Issue by jonasrauber** [evaluating-adversarial-robustness/adv-eval-paper#6]
Who and when will update the PDF? How do we avoid probelems like this in the future?

Maybe having the PDF as a release rather than inside the repo would be better? Or we could consider some webservice that automatically updates the PDF on each commit.

**Comment by carlini** [comment]
Ah, whoops. This was my mistake when creating the repository. 

I was going to look into seeing if we could set up some continuous integration to automatically re-build the PDF after every PR. Does anyone know if this is easy to do? If not, I believe GitHub has commit hooks and was going to just write a short script to manually setup the CI on a server I have that will automate the pdf build.

For now I'll re-generate the PDF and upload it manually.

**Comment by anishathalye** [comment]
We don't even need our own server -- we can set up Travis CI to do this, and it's pretty easy to do. I can set it up tonight.

(also, +1 on doing releases rather than updating the repo: that way we don't make the git repo grow huge)

**Comment by carlini** [comment]
Right that's what I meant by GitHub's CI--I'm just not sure if functionally it can create releases. If it can then great.

**Comment by anishathalye** [comment]
Yes, I think it can. (iirc it requires releases to be tagged, but it can also do that, it'll just be a kinda useless tag like `commit-xxxxxxx` on top of commit `xxxxxxx`)
